services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: posts
      MYSQL_USER: app
      MYSQL_PASSWORD: docker
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      interval: 1s
      retries: 10

  app:
    build: .
    container_name: app
    ports:
      - "3001:3000"
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_NAME: posts
      DATABASE_USER: app
      DATABASE_PASSWORD: docker
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
